name: shadow_widget
description: "A widget that adds a shadow effect to any Flutter widget."
version: 0.1.0
homepage: https://github.com/suragch/shadow_widget
funding:
  - https://www.buymeacoffee.com/suragchdev
topics:
  - widget
  - shadow

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  golden_toolkit: ^0.15.0

flutter: null

screenshots:
  - description: 'Examples of a shadow being applied to various widgets.'
    path: supplemental/shadow.gif