name: shadow_widget
description: "A widget that adds a shadow effect to any Flutter widget. Supports all platforms."
version: 0.1.1
homepage: https://github.com/suragch/shadow_widget
funding:
  - https://www.buymeacoffee.com/suragchdev
topics:
  - widget
  - shadow

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  golden_toolkit: ^0.15.0

flutter: null

screenshots:
  - description: 'A shadow applied to an Image widget with transparent regions.'
    path: supplemental/hello_dart_shadow.png